### ISSUE TITLE
Subheadings aren't displaying right

### ISSUE THREAD

**Issue by SteGriff** [dmleong/dmleong.github.io#1]
Hi! I like your blog

It looks like the headings aren't working right in kramdown because they're missing spaces between the hash characters and the title itself.

![subheadings](https://cloud.githubusercontent.com/assets/3997617/23063046/7c939ac2-f500-11e6-86ef-c64eed55d82e.PNG)

I will try and fix this on one or two posts if you don't mind!

Have a lovely day

**Comment by dmleong** [comment]
Thanks for the fix @SteGriff !
